name:                fastpaced
version:             1.0.0.0
github:              "davnn/fastpaced"
license:             BSD3
author:              "David Muhr"
maintainer:          "muhrdavid+git@gmail.com"
copyright:           "David Muhr"
description:         Please see the README on Github at <https://github.com/davnn/fastpaced#readme>

extra-source-files:
- README.md

dependencies:
- base >= 4.18 && < 5
- hakyll
- pandoc
- filepath
- text

executables:
  fastpaced:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
